### ISSUE TITLE
Where is my litentry after bridgetransfer: transfernative?

### ISSUE THREAD

**Issue by jacksonbaleeiro** [colorfulnotion/polkaholic#292]
Account	 [48VhCQj6oixxcnmbtQBCftTCh8YJKrhDEgEKEZj4Ytzvi36x](https://polkaholic.io/account/0x5c7870c421bbeafddaa7bb8d0b66bdcd19a56c2d7f7ec2c1c8b0055f102cf201)

Chain	[Litentry](https://polkaholic.io/blocks/litentry)
Extrinsic Hash | 0x0b755a79b256976f44dfa4c987241bf09e81353088139575ce2d1f422a9a84fd
-- | -- | -- | -- | -- | --

Params	
amount	[28721324838788](tel:28721324838788)
recipient	0xc484fa984fcf1b9a5438e25492d2d44d5e386fdc
dest_id	0

**Comment by mkchungs** [comment]
According to Litentry team, your LIT token went to ethereum mainnet after the bridgetransfer. Here's the response I got from the team:

The user bridge LIT from the parachain to eth erc 20, it goes to this wallet address : 0xc484fa984fcf1b9a5438e25492d2d44d5e386fdc
https://etherscan.io/address/0xc484fa984fcf1b9a5438e25492d2d44d5e386fdc

(txn: https://etherscan.io/tx/0x2956ed1ece9215ec0b8350e680b807f547689cd3eca52e1f2da90dffdabe1bcf)

If you have further question. please contact Litentry directly. thank you
