### ISSUE TITLE
DOT price in UI wrong compared to coinbase current price

### ISSUE THREAD

**Issue by gallak87** [colorfulnotion/polkaholic#94]
The UI polkadot.polkaholic.io shows a price of $8.47

<img width="268" alt="image" src="https://user-images.githubusercontent.com/7332016/185972227-8af10239-dd9c-4758-9b07-ef5cfcd8972a.png">

But coinbase is pricing at $7.23

<img width="493" alt="image" src="https://user-images.githubusercontent.com/7332016/185972336-f1a9b68e-61e2-4772-a8ca-aef0d429aa33.png">

Where is this price sourced from? It is significantly wrong, causing all calculations on the page to be completely wrong.

**Comment by sourabhniyogi** [comment]
Thank you for your report, we have addressed the issue [we updated our full nodes to use smaller disks over the last week but some crons needed to be copied over and we lost them in the process] -- the data comes from the coingecko API.  We attempt to update to get the data every 5 mins and will make the source and the last time fetch clearer soon.

**Comment by gallak87** [comment]
Thanks, confirmed this is fixed
